# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BostonHacks
email: contact@bostonhacks.io
description: >- # this means to ignore newlines until "baseurl:"
  BostonHacks - Boston's premier collegiate MLH hackathon.
  Join over 450 students in a weekend of hacking, learning, and fun.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://museo.bostonhacks.io"
twitter_username: boston_hacks
github_username:  bostonhacks

# Build settings
markdown: kramdown

nextHackathon:
  name: BostonHacks 2018
  date: November 10th - 11th, 2018
  location: Boston University

# set this to either "noLanding" or "landing"
landingStatus: noLanding

google_analytics: UA-67825496-10

# commented the following out
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - bootstrap-4.0.0
  # - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  - vendor
